import * as elements from './elements.js'

const toggleVisibility = (visibility, element) => {
    // function to change the visibility of element
    element.style.display = visibility;
}

window.onload = () => {
    // for navigation among multiple content elements by using visibility property
    elements.homeElement.addEventListener('click', () => {
        toggleVisibility('block', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.universityElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('block', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.jobElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('block', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.bankElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('block', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.gymElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('block', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.mallElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('block', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.worshipElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('block', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.clubElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('block', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.restaurantElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('block', elements.restaurantContentElement)
        toggleVisibility('none', elements.spaContentElement)
    })
    elements.spaElement.addEventListener('click', () => {
        toggleVisibility('none', elements.homeContentElement)
        toggleVisibility('none', elements.universityContentElement)
        toggleVisibility('none', elements.jobContentElement)
        toggleVisibility('none', elements.bankContentElement)
        toggleVisibility('none', elements.gymContentElement)
        toggleVisibility('none', elements.mallContentElement)
        toggleVisibility('none', elements.worshipContentElement)
        toggleVisibility('none', elements.clubContentElement)
        toggleVisibility('none', elements.restaurantContentElement)
        toggleVisibility('block', elements.spaContentElement)
    })
}
